### ISSUE TITLE
Make Issue

### ISSUE THREAD

**Issue by KyleBehiels** [devrikx/atheros#1]
Make command failed with the following error on Ubuntu 18.4. I have replicated it twice on fresh installs.

```
/home/kyle/atheros/wil6210/cfg80211.c: In function ‘wil_probe_client_handle’:
/home/kyle/atheros/wil6210/cfg80211.c:1809:2: error: too many arguments to function ‘cfg80211_probe_status’
  cfg80211_probe_status(ndev, sta->addr, req->cookie, alive,
  ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/kyle/atheros/wil6210/cfg80211.c:21:0:
./include/net/cfg80211.h:5750:6: note: declared here
 void cfg80211_probe_status(struct net_device *dev, const u8 *addr,
      ^~~~~~~~~~~~~~~~~~~~~
scripts/Makefile.build:332: recipe for target '/home/kyle/atheros/wil6210/cfg80211.o' failed
make[2]: *** [/home/kyle/atheros/wil6210/cfg80211.o] Error 1
scripts/Makefile.build:606: recipe for target '/home/kyle/atheros/wil6210' failed
make[1]: *** [/home/kyle/atheros/wil6210] Error 2
Makefile:1552: recipe for target '_module_/home/kyle/atheros' failed
make: *** [_module_/home/kyle/atheros] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
```
Command

`make -C /lib/modules/$(uname -r)/build M=$(pwd) modules`

Thank you for doing this. Excited for this to be working!

edit: Spelling

**Comment by kirvedx** [comment]
I apologize I did not see your issue until today -

Are you using kernel version **4.17**+ ? If so you'll want to check out the **4.15** or **4.16** branch and use that code base instead.

```bash
git checkout 4-XX-stable
```

Where XX is the minor version of your system's kernel.

---

I'll double check the situation - but pretty sure that the issue I ran into on Debian was: 

* Using the modified 4.15/4.16 kernel source driver on a 4.17 based system produced an error for that same file/function stating that I was not passing enough arguments to the invocation.

So it'd seem sensible to me that if you're using the modified 4.17 kernel source driver (the master branch) on a kernel < 4.17, then you will get an error that too many arguments were passed.

You can see which version of the kernel you are using by running the following:

```bash
rik@devrikx:~$ uname -r
4.17.0-3-amd64
```

Let me know if you are using the correct branch for the kernel you're running, and I'll help you figure it out. I know how frustrating it can be.  Even if you are on kernel 4.17 -> you could always try using the 4.16 branch just to see if that works for you, since that's the version where that method takes fewer arguments.

Best regards -

**Comment by kirvedx** [comment]
I'm going to close this due to there being several updates to the repository since this issue was opened.

Try using one of the kernels we've verified support for (up-to-and-including 5.5 #5, #6). If you're still having problems please submit another issue!
